---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    name: monitoring
    purpose: "network-monitoring"
    environment: "production"
  annotations:
    description: "Network monitoring and diagnostics namespace"
    contact: "ops@company.internal"