---
# ServiceAccount for network monitoring service
apiVersion: v1
kind: ServiceAccount
metadata:
  name: network-monitoring
  namespace: monitoring
  labels:
    app: network-monitoring
    component: service-account
  annotations:
    description: "Service account for network monitoring operations"

---
# Role for network monitoring permissions
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: network-monitoring
  namespace: monitoring
  labels:
    app: network-monitoring
    component: rbac
rules:
  # Allow access to configmaps and secrets for configuration
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "list", "watch", "update", "patch"]

  # Allow access to pods for health monitoring
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]

  # Allow access to events for logging
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]

  # Allow access to deployments for self-management
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets"]
    verbs: ["get", "list", "watch", "update", "patch"]

  # Allow access to cronjobs for scheduling
  - apiGroups: ["batch"]
    resources: ["cronjobs", "jobs"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---
# RoleBinding for network monitoring service
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: network-monitoring
  namespace: monitoring
  labels:
    app: network-monitoring
    component: rbac-binding
subjects:
  - kind: ServiceAccount
    name: network-monitoring
    namespace: monitoring
roleRef:
  kind: Role
  name: network-monitoring
  apiGroup: rbac.authorization.k8s.io

---
# ClusterRole for broader monitoring permissions (if needed)
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: network-monitoring-cluster
  labels:
    app: network-monitoring
    component: cluster-rbac
rules:
  # Allow node access for network monitoring
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]

  # Allow access to network policies
  - apiGroups: ["networking.k8s.io"]
    resources: ["networkpolicies"]
    verbs: ["get", "list", "watch"]

---
# ClusterRoleBinding for cluster-level permissions
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: network-monitoring-cluster
  labels:
    app: network-monitoring
    component: cluster-rbac-binding
subjects:
  - kind: ServiceAccount
    name: network-monitoring
    namespace: monitoring
roleRef:
  kind: ClusterRole
  name: network-monitoring-cluster
  apiGroup: rbac.authorization.k8s.io