---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: zk-communist-build-pipeline
  namespace: flux-system
  labels:
    app: zk-communist
    component: ci-cd
  annotations:
    description: "CI/CD pipeline for ZK-Communist Network Monitoring Service"

spec:
  params:
  - name: git-revision
    type: string
    description: Git revision to build
    default: main
  - name: git-url
    type: string
    description: Git repository URL
    default: "ssh://git@github.com:yourorg/zk-communist.git"
  - name: image-registry
    type: string
    description: Container registry URL
    default: "registry.company.internal/zk-communist"
  - name: image-tag
    type: string
    description: Container image tag
    default: "latest"

  workspaces:
  - name: shared-workspace
    description: Shared workspace for the pipeline
  - name: docker-credentials
    description: Docker registry credentials

  tasks:
  - name: git-clone
    taskRef:
      name: git-clone
      kind: ClusterTask
    params:
    - name: url
      value: $(params.git-url)
    - name: revision
      value: $(params.git-revision)
    workspaces:
    - name: output
      workspace: shared-workspace

  - name: security-scan
    taskRef:
      name: security-scan
      kind: ClusterTask
    runAfter:
    - git-clone
    params:
    - name: source-dir
      value: $(workspaces.shared-workspace.path)/zk-communist
    workspaces:
    - name: source
      workspace: shared-workspace

  - name: build-image
    taskRef:
      name: buildah
      kind: ClusterTask
    runAfter:
    - git-clone
    - security-scan
    params:
    - name: IMAGE
      value: "$(params.image-registry):$(params.image-tag)"
    - name: DOCKERFILE
      value: "$(workspaces.shared-workspace.path)/zk-communist/Dockerfile"
    - name: CONTEXT
      value: "$(workspaces.shared-workspace.path)/zk-communist"
    workspaces:
    - name: source
      workspace: shared-workspace
    - name: dockerconfig
      workspace: docker-credentials

  - name: vulnerability-scan
    taskRef:
      name: trivy-scanner
      kind: ClusterTask
    runAfter:
    - build-image
    params:
    - name: IMAGE_URL
      value: "$(params.image-registry):$(params.image-tag)"
    workspaces:
    - name: source
      workspace: shared-workspace

  - name: deploy-to-staging
    taskRef:
      name: kubernetes-deploy
      kind: ClusterTask
    runAfter:
    - build-image
    - vulnerability-scan
    params:
    - name: NAMESPACE
      value: "monitoring"
    - name: MANIFEST_DIR
      value: "$(workspaces.shared-workspace.path)/zk-communist-gitops"
    - name: IMAGE_TAG
      value: "$(params.image-tag)"
    workspaces:
    - name: source
      workspace: shared-workspace

  - name: integration-tests
    taskRef:
      name: integration-tests
      kind: ClusterTask
    runAfter:
    - deploy-to-staging
    params:
    - name: SERVICE_URL
      value: "http://network-monitoring.monitoring.svc.cluster.local:8012"
    - name: TEST_NAMESPACE
      value: "monitoring"

  finally:
  - name: cleanup
    taskRef:
      name: cleanup-workspace
      kind: ClusterTask
    params:
    - name: WORKSPACE_PATH
      value: $(workspaces.shared-workspace.path)

---
# PipelineRun for automated builds
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: zk-communist-build-$(date +%Y%m%d-%H%M%S)
  namespace: flux-system
  labels:
    app: zk-communist
    component: ci-cd
  annotations:
    pipeline.tekton.dev/release: "latest"

spec:
  pipelineRef:
    name: zk-communist-build-pipeline
  params:
  - name: git-revision
    value: "main"
  - name: git-url
    value: "ssh://git@github.com:yourorg/zk-communist.git"
  - name: image-registry
    value: "registry.company.internal/zk-communist"
  - name: image-tag
    value: "1.0.0"

  workspaces:
  - name: shared-workspace
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  - name: docker-credentials
    secret:
      secretName: registry-credentials